import { Section } from "./Section.js";
import { Job } from "./Job.js";
import { Pill } from "./Pill.js";

const skills = {
  "Back End": [
    "Python",
    "Flask",
    "FastAPI",
    "Strawberry (GraphQL)",
    "SQLModel (SQLAlchemy Wrapper)",
    "Node.JS",
    "Express",
    "Apollo",
    "Postgraphile",
  ],
  "Front End": [
    "Typescript",
    "NextJS",
    "React",
    "Apollo",
    "Redux",
    "Zustand",
    "Tailwind-UI",
    "Material-UI",
    "ChakraUI",
  ],
  Architecture: [
    "Apollo",
    "PostgresQL",
    "DynamoDB",
    "Firebase",
    "Google Apps Script",
    "Chrome Extensions",
    "Slack Apps",
    "NX (Monorepo)",
  ],
  DevOps: [
    "GCP",
    "AWS",
    "Heroku",
    "Github Actions",
    "Helm",
    "Kubernetes",
    "Terraform",
  ],
};

export const Resume = () => {
  return (
    <div className="w-full h-full p-4 text-primary-200">
      <header className="text-center mb-12">
        <h1 className="text-5xl font-mono font-bold text-accent-500 mb-2 uppercase">
          Dave Cook
        </h1>
        <p className="text-xl text-primary-100 font-mono">
          Senior Fullstack Engineer
        </p>
        <div className="flex justify-center gap-4 mt-2 text-sm text-accent-500"></div>
      </header>

      <Section title="Skills">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {Object.entries(skills).map(([category, skillList]) => (
            <div key={category}>
              <h3 className="font-bold text-lg text-accent-600 mb-3">
                {category}
              </h3>
              <div className="flex flex-wrap gap-2">
                {skillList.map((skill) => (
                  <Pill key={skill}>{skill}</Pill>
                ))}
              </div>
            </div>
          ))}
        </div>
      </Section>

      <Section title="Software Development Experience">
        <div className="space-y-8">
          <Job
            title="Senior Fullstack Engineer"
            company="Miruni.io"
            period="Jun 2023 - Jun 2024"
            location="Remote"
            description="Principal full-stack developer in a small team of a productivity SaaS startup. In a team of varying size but mainly limited to 2-3 developers, I was the only engineer responsible for managing every aspect of the application."
            achievements={[
              "Designed and implemented integrations with Zapier, Slack, and Jira.",
              "Managed graphql backend using the Postgraphile framework, requiring business logic to be managed at the database level (Postgres) using stored procedures and row level security for implementing a granular permissions system.",
              "Ensured efficiency at scale by analyzing Postgres query plans and identifying opportunities for improvement.",
              "Implemented detailed event tracking systems using Newrelic and Posthog to gain insight on the user experience and to identify pain points.",
              "Managed CI/CD pipelines using Github Actions, Terraform, and Helm to ensure smooth deployment to AWS AppRunner, Lambda, and EKS Kubernetes depending on the development environment.",
              "Improved page load times dramatically by investigating client side React rendering, identifying inefficiencies and taking advantage of dynamic and lazy loading to improve user experience.",
            ]}
          />
          <Job
            title="Senior Fullstack Engineer"
            company="Turn Technologies"
            period="2022 - Jun 2023"
            location="Remote"
            description="Following excellent feedback in my previous position, I was invited to act as the sole-backend engineer in creating the new, AI-powered product, Advise. As the product grew, I was the principal backend engineer in a small team."
            achievements={[
              "Developed framework for moving to backend microservice infrastructure within upcoming products. My template app is used by at least 3 products within Turn Technologies.",
              "Created CI/CD flow using Github actions and Heroku.",
              "Ensured 80%+ test coverage across repos using Jest and Pytest frameworks.",
              "Created and maintained backend service which received and stored data generated by the Data Science team and served it to the front end via graphQL.",
              "Designed and implemented a centralized authentication system which processed Auth0 validation and could be used by various products.",
              "Instigated transition to Typescript in front-end repositories.",
              "Synchronized with DevOps team on transferring infrastructure from Heroku to AWS EC2 instances managed by Jenkins.",
              "Implemented Figma designs in React front end, including Google Maps API integration with custom datalayer overlay.",
            ]}
          />
          <Job
            title="Senior Engineering Support"
            company="Turn Technologies"
            period="2021 - mid 2022"
            location="Remote"
            description="Provided timely support and hot fixes for bugs in production applications."
            achievements={[
              "Added functionality to internal admin apps to improve support efficiency (Flask-Admin).",
              "Created efficiency-boosting tools for support staff (Google Apps Script).",
              "Main developer for Turn integrations with Lever & Rippling ATS external APIs.",
            ]}
          />
          <Job
            title="Freelance Integrations Developer"
            company="Independent"
            period="2018 - 2021"
            location="Remote"
            description="Successful freelance business as a freelance developer and automations specialist, acting as a long-term on-call resource and consultant to international businesses. Solving business needs for technical and non-technical clients using appropriate technologies and tools for the task at hand."
            achievements={[
              "Created Zapier custom apps (Node.js) for Airtable, Monday.com, Basecamp, TrackHS, ClickUp, Dropbox, Zoom, Squarespace, Smartsheets, Shopify, among many others.",
              "Custom Google Chrome extensions for increasing productivity (eg custom buttons to make changes in Copper CRM from GMail’s UI).",
              "Independently developed booking app for contracting firm using Firebase Functions as a backend, and a react frontend and integrations with Google Calendar and Google forms.",
            ]}
          />
        </div>
      </Section>

      <Section title="Other Work Experience">
        <div className="space-y-4">
          <p>Head of ESL Department, Vinschool, Hanoi, Vietnam (2018-2019)</p>
          <p>English Teacher, Colegio Álamos, Querétaro, Mexico (2016-2018)</p>
          <p>ALT Teacher, Kagoshima, Japan (2015-2016)</p>
        </div>
      </Section>

      <Section title="Education">
        <div className="space-y-4">
          <p>
            <span className="font-bold">MA TESOL</span> - University of
            Birmingham
          </p>
          <p>
            <span className="font-bold">BA European Languages</span> -
            University of Aberystwyth
          </p>
        </div>
      </Section>

      <Section title="Languages">
        <div className="flex justify-around md:justify-start md:gap-12">
          <p>
            <span className="font-bold">English:</span> Native Speaker
          </p>
          <p>
            <span className="font-bold">Spanish:</span> Fluent
          </p>
          <p>
            <span className="font-bold">French:</span> Intermediate
          </p>
        </div>
      </Section>
    </div>
  );
};
